//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorting_Hat_Final {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form11 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form11() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorting_Hat_Final.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnPlay_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnPlay.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=3}.
        /// </summary>
        public static System.Drawing.Point btnPlay_Location {
            get {
                object obj = ResourceManager.GetObject("btnPlay.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        /// </summary>
        public static System.Windows.Forms.Padding btnPlay_Margin {
            get {
                object obj = ResourceManager.GetObject("btnPlay.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=98, Height=43}.
        /// </summary>
        public static System.Drawing.Size btnPlay_Size {
            get {
                object obj = ResourceManager.GetObject("btnPlay.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int btnPlay_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnPlay.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string btnPlay_Text {
            get {
                return ResourceManager.GetString("btnPlay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnStop_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnStop.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=117,Y=3}.
        /// </summary>
        public static System.Drawing.Point btnStop_Location {
            get {
                object obj = ResourceManager.GetObject("btnStop.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        /// </summary>
        public static System.Windows.Forms.Padding btnStop_Margin {
            get {
                object obj = ResourceManager.GetObject("btnStop.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=98, Height=43}.
        /// </summary>
        public static System.Drawing.Size btnStop_Size {
            get {
                object obj = ResourceManager.GetObject("btnStop.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int btnStop_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnStop.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string btnStop_Text {
            get {
                return ResourceManager.GetString("btnStop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=8.1, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font button1_Font {
            get {
                object obj = ResourceManager.GetObject("button1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode button1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("button1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=209,Y=856}.
        /// </summary>
        public static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding button1_Margin {
            get {
                object obj = ResourceManager.GetObject("button1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=605, Height=127}.
        /// </summary>
        public static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button1.
        /// </summary>
        public static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=8.1, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font button2_Font {
            get {
                object obj = ResourceManager.GetObject("button2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode button2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("button2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1084,Y=856}.
        /// </summary>
        public static System.Drawing.Point button2_Location {
            get {
                object obj = ResourceManager.GetObject("button2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding button2_Margin {
            get {
                object obj = ResourceManager.GetObject("button2.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=605, Height=127}.
        /// </summary>
        public static System.Drawing.Size button2_Size {
            get {
                object obj = ResourceManager.GetObject("button2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int button2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button2.
        /// </summary>
        public static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=8.1, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font button3_Font {
            get {
                object obj = ResourceManager.GetObject("button3.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode button3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("button3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=209,Y=1028}.
        /// </summary>
        public static System.Drawing.Point button3_Location {
            get {
                object obj = ResourceManager.GetObject("button3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding button3_Margin {
            get {
                object obj = ResourceManager.GetObject("button3.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=605, Height=127}.
        /// </summary>
        public static System.Drawing.Size button3_Size {
            get {
                object obj = ResourceManager.GetObject("button3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int button3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button3.
        /// </summary>
        public static string button3_Text {
            get {
                return ResourceManager.GetString("button3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=8.1, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font button4_Font {
            get {
                object obj = ResourceManager.GetObject("button4.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode button4_ImeMode {
            get {
                object obj = ResourceManager.GetObject("button4.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1084,Y=1018}.
        /// </summary>
        public static System.Drawing.Point button4_Location {
            get {
                object obj = ResourceManager.GetObject("button4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding button4_Margin {
            get {
                object obj = ResourceManager.GetObject("button4.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=605, Height=127}.
        /// </summary>
        public static System.Drawing.Size button4_Size {
            get {
                object obj = ResourceManager.GetObject("button4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int button4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button4.
        /// </summary>
        public static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string langSelecBox_Items {
            get {
                return ResourceManager.GetString("langSelecBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string langSelecBox_Items1 {
            get {
                return ResourceManager.GetString("langSelecBox.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (default).
        /// </summary>
        public static string langSelecBox_Items2 {
            get {
                return ResourceManager.GetString("langSelecBox.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string langSelecBox_Items3 {
            get {
                return ResourceManager.GetString("langSelecBox.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string langSelecBox_Items4 {
            get {
                return ResourceManager.GetString("langSelecBox.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        public static string langSelecBox_Items5 {
            get {
                return ResourceManager.GetString("langSelecBox.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string langSelecBox_Items6 {
            get {
                return ResourceManager.GetString("langSelecBox.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1557,Y=3}.
        /// </summary>
        public static System.Drawing.Point langSelecBox_Location {
            get {
                object obj = ResourceManager.GetObject("langSelecBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        /// </summary>
        public static System.Windows.Forms.Padding langSelecBox_Margin {
            get {
                object obj = ResourceManager.GetObject("langSelecBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=246, Height=39}.
        /// </summary>
        public static System.Drawing.Size langSelecBox_Size {
            get {
                object obj = ResourceManager.GetObject("langSelecBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int langSelecBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("langSelecBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool langSelecLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("langSelecLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode langSelecLabel_ImeMode {
            get {
                object obj = ResourceManager.GetObject("langSelecLabel.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1392,Y=9}.
        /// </summary>
        public static System.Drawing.Point langSelecLabel_Location {
            get {
                object obj = ResourceManager.GetObject("langSelecLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=0,Right=5,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding langSelecLabel_Margin {
            get {
                object obj = ResourceManager.GetObject("langSelecLabel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=150, Height=32}.
        /// </summary>
        public static System.Drawing.Size langSelecLabel_Size {
            get {
                object obj = ResourceManager.GetObject("langSelecLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int langSelecLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("langSelecLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string langSelecLabel_Text {
            get {
                return ResourceManager.GetString("langSelecLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=209,Y=81}.
        /// </summary>
        public static System.Drawing.Point pictureBox1_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=3,Right=4,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding pictureBox1_Margin {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1479, Height=659}.
        /// </summary>
        public static System.Drawing.Size pictureBox1_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to StretchImage.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox1_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int pictureBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=14.1, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font shQuestion_Font {
            get {
                object obj = ResourceManager.GetObject("shQuestion.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode shQuestion_ImeMode {
            get {
                object obj = ResourceManager.GetObject("shQuestion.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=199,Y=742}.
        /// </summary>
        public static System.Drawing.Point shQuestion_Location {
            get {
                object obj = ResourceManager.GetObject("shQuestion.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding shQuestion_Margin {
            get {
                object obj = ResourceManager.GetObject("shQuestion.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1523, Height=110}.
        /// </summary>
        public static System.Drawing.Size shQuestion_Size {
            get {
                object obj = ResourceManager.GetObject("shQuestion.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int shQuestion_TabIndex {
            get {
                object obj = ResourceManager.GetObject("shQuestion.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string shQuestion_Text {
            get {
                return ResourceManager.GetString("shQuestion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment shQuestion_TextAlign {
            get {
                object obj = ResourceManager.GetObject("shQuestion.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
    }
}
